<identifier> ::= <letter> | <symbol> <letter or digit>

<letter> ::= A | B | C  | X | Y | Z

<digit> ::= 0 | 1 | 2 | 7 | 8 | 9

<letter or digit> ::= <letter> | <digit>

<number> ::= <decimal> | <hexadecimal>

<decimal> ::= <digit> | <digit> <decimal>


<hexadecimal> ::= <hexdigit> | <hexdigit> <hexadecimal>


<hexdigit> ::= <digit> | A | B | C | D | E | F