package com.bloxbean.algodea.idea.codegen.service.util;

public enum TxnType {
    APP_CREATE, APP_CALL, APP_OPTIN, APP_DELETE, APP_UPDATE, APP_CLOSEOUT, APP_CLEARSTATE, READ_STATE,
    LOGIC_SIG_DELEGATION, LOGIC_SIG_CONTRACT,
    ASSET_CFG_CREATE, ASSET_CFG_MODIFY, ASSET_OPTIN, ASSET_FRZ, ASSET_UNFRZ, ASSET_CFG_DESTROY, ASSET_REVOKE,
    TRANSFER_ALGO, TRANSFER_ASA
}
